### ISSUE TITLE
`jrplot_iucn()` missing categories

### ISSUE THREAD

**Issue by AMBarbosa** [Henning-Winker/JARA#11]
I'm not sure if this is "normal" behaviour, but it sure has me confused, so I think it warrants either a fix or an explanation in the function help file. The output plot of `jrplot_iucn()` often shows colours and legend for only 4 IUCN categories, while the category / status reported in the console output is the one missing in the plot. Example:
```
dat <- data.frame(year = 2012:2022, abundance = c(710, 243, 584, 455, 735, 705, 543, 548, 455, 536, 310))

jr <- build_jara(dat)

set.seed(2)
fit <- fit_jara(jr)

out <- jrplot_iucn(fit)

out
# $perc.risk
#           Pr.Decl change3GL CR EN VU LC
# perc.risk    89.4     -32.8  0  1 17 45
# 
# $status
# [1] "NT"
```
![image](https://github.com/Henning-Winker/JARA/assets/12085508/ef77c629-0cf6-415c-ae8d-ab0fad6ec443)

So, the output 'status' is "NT", but "NT" is neither in the plot nor in the 'perc.risk' section of the output. These include only 4 categories, whose probabilities add up to 100%. What am I missing?

Oddly enough, with a different random seed, the plot may get all the categories but the console output status is NA:

```
set.seed(123)
fit <- fit_jara(jr)

out <- jrplot_iucn(fit)

out
# $perc.risk
#           Pr.Decl change3GL CR EN VU NT LC
# perc.risk    86.7     -28.7  0 15 32 16 37
# 
# $status
# [1] NA
```
![image](https://github.com/Henning-Winker/JARA/assets/12085508/b33a4d60-0456-4e60-8ddb-b6ebb63647bd)

A fix or an explanation would be greatly appreciated. Cheers!

**Comment by rbsherley** [comment]
Hi @AMBarbosa - thanks for flagging this. 
We recently added NT as a user specified option (NT_opt=TRUE), but there was a bug in how it was behaving. I think I have fixed it now. But, please note that JARA will return NT in some circumstances even if NT_opt=FALSE. This is to reflect that NT can be used when there is uncertainty and the range of plausible categories includes LC, VU and/or EN. I've updated the README file to reflect this (sorry, we had forgotten to do that!).

Please could you check if the code below now behaves as expected for you (it does for me). Thanks a lot, Richard

library(devtools)
install_github("Henning-Winker/JARA",force=T)
library(JARA)

dat <- data.frame(year = 2012:2022, abundance = c(710, 243, 584, 455, 735, 705, 543, 548, 455, 536, 310))

jr <- build_jara(dat)

set.seed(2)
fit1 <- fit_jara(jr)

jrplot_iucn(fit1, NT_opt=FALSE)
jrplot_iucn(fit1, NT_opt=TRUE)
jrplot_iucn(fit1)


set.seed(123)
fit2 <- fit_jara(jr)

jrplot_iucn(fit2, NT_opt=FALSE)
jrplot_iucn(fit2, NT_opt=TRUE)
jrplot_iucn(fit2)

**Comment by AMBarbosa** [comment]
Many thanks for your swift and clear response! The `?jrplot_iucn` help file does not mention the `NT_opt` argument. Anyway, your code now does work as expected for me, for this and the other species I'm analyzing. Cheers!

**Comment by rbsherley** [comment]
Sorry - forgot to update the documentation. It should be there now.
