### ISSUE TITLE
readme: describe steps for actually using this DST

### ISSUE THREAD

**Issue by trashbirdecology** [Henning-Winker/JARA#2]
A few comments for improving the usability of this repository/JARA:
1. The readme currently does not describe how to actually deploy the tool. At the top would be helpful to have section e.g. 
        > ##How to use this tool
        > Step 1. Clone or download the repository
        > Step 2. Edit and run script.R, etc...

2. I suggest removing the text which looks like it was meant for a non-github location (e.g., "To ensure to a high degree of transparency and reproducibility, JARA is hosted online on the global open-source platform GitHub (https://github.com/henning-winker/JARA).")

3. Update the reference to the [bioarxiv preprint](https://www.biorxiv.org/content/10.1101/672899v2.article-info) to your Conservation Biology paper.

4. Create a vignette  and/or:

5. Outline the readme such that it provides code, rather than a series of figures and figure descriptions. E.g., This function does this, here's an example of the pretty figure it generates.

P.S. Sweet graphics (but maybe not CB-friendly? Idk)

**Comment by Henning-Winker** [comment]
Thanks a lot for the feedback. I am only seeing this now.
JARA is currently converted into a R package and should be fully functional by next week, including a vignette :)

Then indeed working on changing the preprint to a journal ;)

**Comment by trashbirdecology** [comment]
Cool!
